x-default-logging: &logging
  driver: json-file
  options:
    max-file: 2
    max-size: 5m

services:
  postgres:
    # command: []
    container_name: postgres
    # depends_on: []
    environment:
      POSTGRES_DB: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_USER: gorm
    extra_hosts:
      - host.docker.internal:host-gateway
    # healthcheck: {}
    image: postgres:latest
    labels:
      namespace: postgres
    logging: *logging
    # platform: linux/amd64
    ports:
      - "5432:5432"
    restart: "no"

  postgress-migrate:
    command:
      - sql
      - --file=/init_schema.up.sql
      - --host=postgres:5432
      - --insecure
    container_name: postgress-migrate
    depends_on:
      postgress:
        condition: service_healthy
    # environment: []
    extra_hosts:
      - host.docker.internal:host-gateway
    # healthcheck: {}
    image: postgres:16.2
    labels:
      namespace: postgress-migrate
    logging: *logging
    # platform: linux/amd64
    # ports: []
    restart: "no"
    volumes:
      - ./db/init_schema.up.sql:/init_schema.up.sql:ro

  postgress-migrate-cmd:
    # command: []
    container_name: postgress-migrate-cmd
    depends_on:
      postgress-migrate:
        condition: service_completed_successfully
    entrypoint:
      - /bin/sh
      - -c
      - -Eefuvx
      - >-
        ./postgress-migrate.sh postgress
    environment: []
    extra_hosts:
      - host.docker.internal:host-gateway
    # healthcheck: {}
    image: migrate/migrate:v4.17.1
    labels:
      namespace: postgress-migrate-cmd
    logging: *logging
    # platform: linux/amd64
    # ports: []
    restart: "no"
    volumes:
      - ./db/server/:/db/server/:ro
      - ./script/postgress-migrate.sh:/postgress-migrate.sh:ro
